apiVersion: apps/v1
kind: Deployment
metadata:
  name: buzz-server
  labels:
    name: buzz-server
spec:
  selector:
    matchLabels:
      name: buzz-server
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        name: buzz-server
    spec:
      containers:
        - name: buzz-server
          image: buzzrealtime/server:0.0.4
          env:
            - name: PUBSUB_PROJECT_ID
              value: "my-project-id"
            - name: PUBSUB_EMULATOR_HOST
              value: "pubsub-emulator:8681"
            - name: BIGTABLE_EMULATOR_HOST
              value: "bigtable-emulator:9035"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: buzz-server
spec:
  selector:
    name: buzz-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-emulator
  labels:
    name: pubsub-emulator
spec:
  selector:
    matchLabels:
      name: pubsub-emulator
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        name: pubsub-emulator
    spec:
      containers:
        - name: pubsub-emulator
          image: messagebird/gcloud-pubsub-emulator:latest
          env:
            - name: PUBSUB_PROJECT_ID
              value: "my-project-id"
          ports:
            - containerPort: 8681
---
apiVersion: v1
kind: Service
metadata:
  name: pubsub-emulator
spec:
  selector:
    name: pubsub-emulator
  ports:
    - protocol: TCP
      port: 8681
      targetPort: 8681
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigtable-emulator
  labels:
    name: bigtable-emulator
spec:
  selector:
    matchLabels:
      name: bigtable-emulator
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        name: bigtable-emulator
    spec:
      containers:
        - name: bigtable-emulator
          image: shopify/bigtable-emulator
          ports:
            - containerPort: 9035
---
apiVersion: v1
kind: Service
metadata:
  name: bigtable-emulator
spec:
  selector:
    name: bigtable-emulator
  ports:
    - protocol: TCP
      port: 9035
      targetPort: 9035
