#apiVersion: cert-manager.io/v1alpha2
#kind: ClusterIssuer
#metadata:
#  name: letsencrypt-staging
#  namespace: cert-manager
#spec:
#  acme:
#    server: https://acme-staging-v02.api.letsencrypt.org/directory
#    email: nicolas.gerelm@gmail.com
#    privateKeySecretRef:
#      name: letsencrypt-staging
#    solvers:
#      - http01:
#          ingress:
##            class:  nginx
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress2
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - buzz.bobby-demo.site
      secretName: tls-bobby
  rules:
    - host: buzz.bobby-demo.site
      http:
        paths:
          - backend:
              serviceName: buzz-server
              servicePort: 80



#apiVersion: cert-manager.io/v1alpha2
#kind: ClusterIssuer
#metadata:
#  name: letsencrypt-prod
#  namespace: cert-manager
#spec:
#  acme:
#    # The ACME server URL
#    server: https://acme-v02.api.letsencrypt.org/directory
#    # Email address used for ACME registration
#    email: nicolas.gerelm@gmail.com
#    # Name of a secret used to store the ACME account private key
#    privateKeySecretRef:
#      name: letsencrypt-prod
#    # Enable the HTTP-01 challenge provider
#    solvers:
#      - http01:
#          ingress:
#            class: nginx
